import Head from "next/head";
import Image from "next/image";
import { Inter } from "next/font/google";
import styles from "@/styles/Home.module.css";
import Link from "next/link";
import { useEffect } from "react";
import { useRouter } from "next/router";

const inter = Inter({ subsets: ["latin"] });

export default function Home() {
  const router = useRouter();

  useEffect(() => {
    setTimeout(() => {
      router.push("/home");
    }, 5000);
  }, []);

  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>
        <div className="flex flex-col items-center justify-center min-h-screen bg-gray-100">
          <div className="max-w-xl p-6 bg-white rounded-lg shadow-md">
            <h1 className="text-4xl font-bold mb-8 text-center">
              Welcome to StudyBuddy
            </h1>
            <p className="text-lg mb-8">
              StudyBuddy is a platform where you can find study resources,
              connect with other students, and schedule tutoring sessions with
              qualified tutors. Whether you need help with math, science,
              history, or any other subject, StudyBuddy has got you covered.
            </p>
            <div className="grid grid-cols-1 md:grid-cols-2 gap-8">
              <Link
                href="/signup"
                className="bg-blue-500 hover:bg-blue-600 text-white font-bold py-4 px-8 rounded-lg transition-colors duration-300 flex items-center justify-center"
              >
                Sign Up
              </Link>
              <Link
                href="/signin"
                className="bg-gray-500 hover:bg-gray-600 text-white font-bold py-4 px-8 rounded-lg transition-colors duration-300 flex items-center justify-center"
              >
                Sign In
              </Link>
            </div>
          </div>
        </div>
      </main>
    </>
  );
}
